//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeWebAPIService
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USR()
        {
            this.USR1 = new HashSet<USR>();
            this.USR11 = new HashSet<USR>();
        }
    
        public int USR_UID { get; set; }
        public string LGN_UID { get; set; }
        public string USR_DSPLY_NAM { get; set; }
        public bool ACTV_FLG { get; set; }
        public Nullable<System.DateTime> EXPRTN_DTE { get; set; }
        public System.DateTime CRET_DTM { get; set; }
        public Nullable<int> CRET_UID { get; set; }
        public Nullable<System.DateTime> LST_UPDT_DTM { get; set; }
        public Nullable<int> LST_UPDT_UID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USR> USR1 { get; set; }
        public virtual USR USR2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USR> USR11 { get; set; }
        public virtual USR USR3 { get; set; }
    }
}
